@startuml

rectangle Model {
    rectangle "Sensor Things"
    rectangle "Map Objekte"
}

rectangle Controller {
    rectangle "Frost"
    rectangle "View-Contoller"
}

rectangle View {
    rectangle "Layout"
    rectangle "MapPage"
    rectangle "DeitailPage"
}

@enduml