@startuml MapPageTest

actor User
participant MapView
participant Map
participant MapController
participant StationConfiguration
participant Legend 
participant StationInfo
participant DataProvider

User -> MapView ++ : open()
MapView -> Map ++ : open()
Map -> MapController ++ : getPins()
MapController -> StationConfiguration ++ : getPins()
StationConfiguration -> DataProvider ++ : getLatestObservations(center, radius, feature)
return observations
StationConfiguration -> DataProvider ++ : getStationsIn(center, radius)
return stations
return pins
return pins
Map -> MapController ++ : getPolygons()
MapController -> StationConfiguration ++ : getPolygons()
return []
return []
MapView -> MapController ++ : getScale()
MapController -> StationConfiguration ++ : getScale()
return scale
return scale
MapView -> Legend ++ : open(scale)

'Nutzer zoomt'
User -> Map ++ : zoom()
Map -> MapController ++ : handleViewportChange(viewport)
MapController -> StationConfiguration ++ : getPins, Polygons wie oben
return pins, polygons
return 
return

'Nutzer wählt Station'
User -> Map ++ : clickOnMarker(pin)
Map -> MapController ++ : handlePopup(pin)
MapController -> DataProvider ++ : getStation(id)
return station
return station
return
@enduml