@startuml Interface
class RequestClass {
    + getLatestObservations(center : Position, radius: int, feature : Feature) : Observation[]
    + getStationsIn(middle: Position, radius : int) : Station[]
    + getHistoricalObservations(station : Station, start : Date, end : Date) : Observation[]
    + getHistoricalObservations(station : Station, start : Date, end : Date, frequency : Frequency, feature : Feature) : Observation[]
    + getScale(feature : Feature) : Scale
    + getStation(id : string) : Station
}
@enduml