@startuml MapPageScenario

actor User

box 'View' #LightGreen
participant MapView
participant Map
participant Legend 
participant StationInfo
end box

box 'Controller' #LightSalmon
participant MapController
participant StationConfiguration

participant DataProvider
end box
User -> MapView ++ : open()
MapView -> Map ++ : open()
Map -> MapController ++ : getPins()
MapController -> StationConfiguration ++ : getPins()
StationConfiguration -> DataProvider ++ : getObservationStations(center, radius)
return stations
loop for every station
StationConfiguration -> DataProvider ++ : getLatestObservations(station, feature)
return observations
end

return pins
return pins
Map -> MapController ++ : getPolygons()
MapController -> StationConfiguration ++ : getPolygons()
return []
return []
MapView -> MapController ++ : getScale()
MapController -> StationConfiguration ++ : getScale()
return scale
return scale
MapView -> Legend ++ : open(scale)

'Nutzer zoomt'
User -> Map ++ : zoom()
Map -> MapController ++ : handleViewportChange(viewport)
note right: Map wird mit neu gerendert, ruft also nochmal getPins() usw auf.
return 
return

'Nutzer wählt Station'
User -> Map ++ : clickOnMarker(pin)
Map -> MapController ++ : handlePopup(pin)
MapController -> DataProvider ++ : getStation(id)
return station
return station
return
@enduml