@startuml View

namespace View {
    namespace Components {
        namespace MapPage {

            'View.Components.Layout.MapPage *-- View.Components.MapPage.MapView
            
            MapView *-- Search
            
            MapView *-- Map
            MapView *-- FeatureSelect
            MapView *-- FeatureInfo

            MapView *-- Legend

            class FeatureSelect {
                + getSelectedFeature() : Feature
                + onConfigurationChanged(conf : MapConfiguration)
            }
            class Search {
                + State.searchTerm : string
                + onSearch(string searchTerm) : void
                + onLocationSearch() : void
                + reset() : void
            }

            class MapView {
                + selectStation(station : Messstation)
                + getValueAt(position: Position, feature : Feature) : number
                + onViewportChange(viewport : Viewport)
                + onStationSelected(pin : MapPin)
            }
            class Map {
                + Props.pins : MapPin[]
                + Props.polygons : Polygon[]
                + Props.onViewportChange()
                + Props.handlePopup(pin : MapPin)
            }
            class Legend {
                + Props.scale : Scale
            }

            Map *-- StationInfo

            class StationInfo {
                + Props.station : ObservationStation
            }

            class FeatureInfo {
                + Props.feature : Feature
            }
        }
        namespace DetailPage {
            class ObservationStationProfile {
                + Props.observationStation: ObservationStation
            }
            class LocationMap {
                + Props.position: Position
            }
            abstract Diagram {
                + props.feature: Feature
                + props.observationStation: ObservationStation
                + getId() : string
            }
            class FeatureHistoryLineChart extends Diagram
            class YearComparisonLineChart extends Diagram
            class ComparisonToLastYearPieChart extends Diagram
        }


        namespace Layout {
            Layout *-- PageMenu
            PageMenu *-- LanguageMenu

            class MapPage
            class DetailPage {
                Props.id: string
            }
            class ErrorPage {
                props.errorCode : number
                props.errorMessage : string
            }
            class PrivacyPolicyPage
            class AboutPage
            class PageMenu
            class LanguageMenu
            class Layout
        }
    }
}

@enduml